name: openreads
description: A new Flutter project.

publish_to: "none"

version: 2.3.0+47

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.1.0
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  path: ^1.8.2
  flutter_displaymode: ^0.6.0
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  flutter_bloc: ^8.1.1
  colours: ^0.0.2
  blurhash: ^1.1.1
  image: ^4.0.15
  fl_chart: ^0.65.0
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  connectivity_plus: ^5.0.1
  http: ^1.0.0
  cached_network_image: ^3.3.0
  loading_animation_widget: ^1.2.0+3
  infinite_scroll_pagination: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  settings_ui: ^2.0.2
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.2.1
  hydrated_bloc: ^9.0.0
  barcode_scan2: ^4.2.1
  intro_slider: ^4.2.0
  flutter_email_sender: ^6.0.0
  permission_handler: ^11.0.0
  filesystem_picker: ^4.0.0
  archive: ^3.3.5
  share_plus: ^7.0.2
  device_info_plus: ^9.0.2
  dynamic_color: ^1.6.2
  image_fade: ^0.6.2
  package_info_plus: ^5.0.1
  animated_widgets: ^1.1.0
  shared_storage: ^0.8.0
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.2
  flutter_typeahead: ^5.0.1
  flex_color_picker: ^3.2.2
  diacritic: ^0.1.4
  flutter_speed_dial: ^7.0.0
  blurhash_dart: ^1.2.1
  csv: ^5.0.2
  file_picker: 5.3.2
  sealed_languages: ^1.0.0
  chip_list: ^2.4.4+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "./assets/icons/icon.png"
  adaptive_icon_foreground: "./assets/icons/icon.png"
  adaptive_icon_background: "#00BFA6"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf
        - asset: assets/fonts/SofiaSans-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
